///|
pub extern "C" fn sinf(x : Float) -> Float = "sinf"

///|
pub extern "C" fn cosf(x : Float) -> Float = "cosf"

///|
pub extern "C" fn tanf(x : Float) -> Float = "tanf"

///|
pub extern "C" fn sinhf(x : Float) -> Float = "sinhf"

///|
pub extern "C" fn coshf(x : Float) -> Float = "coshf"

///|
pub extern "C" fn tanhf(x : Float) -> Float = "tanhf"

///|
pub extern "C" fn asinf(x : Float) -> Float = "asinf"

///|
pub extern "C" fn acosf(x : Float) -> Float = "acosf"

///|
pub extern "C" fn atanf(x : Float) -> Float = "atanf"

///|
pub extern "C" fn atan2f(y : Float, x : Float) -> Float = "atan2f"

///|
pub extern "C" fn asinhf(x : Float) -> Float = "asinhf"

///|
pub extern "C" fn acoshf(x : Float) -> Float = "acoshf"

///|
pub extern "C" fn atanhf(x : Float) -> Float = "atanhf"

///|
pub extern "C" fn logf(x : Float) -> Float = "logf"

///|
pub extern "C" fn log10f(x : Float) -> Float = "log10f"

///|
pub extern "C" fn log2f(x : Float) -> Float = "log2f"

///|
pub extern "C" fn log1pf(x : Float) -> Float = "log1pf"

///|
pub extern "C" fn expf(x : Float) -> Float = "expf"

///|
pub extern "C" fn exp2f(x : Float) -> Float = "exp2f"

///|
pub extern "C" fn expm1f(x : Float) -> Float = "expm1f"

///|
pub extern "C" fn powf(x : Float, y : Float) -> Float = "powf"

///|
pub extern "C" fn sqrtf(x : Float) -> Float = "sqrtf"

///|
pub extern "C" fn cbrtf(x : Float) -> Float = "cbrtf"

///|
pub extern "C" fn hypotf(x : Float, y : Float) -> Float = "hypotf"

///|
pub extern "C" fn ldexpf(x : Float, exp : Int) -> Float = "ldexpf"

///|
pub extern "C" fn scalbnf(x : Float, n : Int) -> Float = "scalbnf"
