
const LOG_MAX_ULP : Int = 1
const LOG2_MAX_ULP : Int = 1
const LOG10_MAX_ULP : Int = 1
const LOG1P_MAX_ULP : Int = 1

const POW_MAX_ULP : Int = 2

const EXP_MAX_ULP : Int = 1
const EXP2_MAX_ULP : Int = 1
const EXP10_MAX_ULP : Int = 1
const EXPM1_MAX_ULP : Int = 1

const CBRT_MAX_ULP: Int = 1

const ATAN_MAX_ULP : Int = 1
const ASIN_MAX_ULP : Int = 1
const ACOS_MAX_ULP : Int = 1


const ACOSH_MAX_ULP : Int = 1
const ASINH_MAX_ULP : Int = 1
const ATANH_MAX_ULP : Int = 2

const COSH_MAX_ULP : Int = 1
const SINH_MAX_ULP : Int = 1
const TANH_MAX_ULP : Int = 2
