///|
const LOG_MAX_ULP : Int = 0

///|
const LOG2_MAX_ULP : Int = 1

///|
const LOG10_MAX_ULP : Int = 0

///|
const LOG1P_MAX_ULP : Int = 0

///|
const POW_MAX_ULP : Int = 2

///|
const EXP_MAX_ULP : Int = 1

///|
const EXP2_MAX_ULP : Int = 1

///|
const EXP10_MAX_ULP : Int = 1

///|
const EXPM1_MAX_ULP : Int = 1

///|
const CBRT_MAX_ULP : Int = 1

///|
const ATAN_MAX_ULP : Int = 0

///|
const ASIN_MAX_ULP : Int = 1

///|
const ACOS_MAX_ULP : Int = 1

///|
const ACOSH_MAX_ULP : Int = 1

///|
const ASINH_MAX_ULP : Int = 1

///|
const ATANH_MAX_ULP : Int = 2

///|
const COSH_MAX_ULP : Int = 1

///|
const SINH_MAX_ULP : Int = 1

///|
const TANH_MAX_ULP : Int = 2

///|
const COS_MAX_ULP : Int = 0

///|
const SIN_MAX_ULP : Int = 0

///|
const TAN_MAX_ULP : Int = 0

///|
const COSPI_MAX_ULP : Int = 49

///|
const SINPI_MAX_ULP : Int = 3
// const TANPI_MAX_ULP : Int = 3

///|
const SQRT_MAX_ULP : Int = 0

///|
const HYPOT_MAX_ULP : Int = 4

///|
const ERF_MAX_ULP : Int = 1

///|
const ERFC_MAX_ULP : Int = 1

///|
const J0_MAX_ULP : Int = 2

///|
const Y0_MAX_ULP : Int = 2

///|
const J1_MAX_ULP : Int = 4

///|
const Y1_MAX_ULP : Int = 2

// const JN_MAX_ULP : Int = 2
// const YN_MAX_ULP : Int = 2

///|
const ERFINV_MAX_ULP : Int = 2

///|
const TGAMMA_MAX_ULP : Int = 4

///|
const LGAMMA_MAX_ULP : Int = 23

///|
const TRIGAMMA_MAX_ULP : Int = 14

///|
const DIGAMMA_MAX_ULP : Int = 1023

///|
const ZETA_MAX_ULP : Int = 3
